application:
  name: java_kafka
server:
  port: 8091

#APP SPECIFIC CUSTOM PROPERTIES
app:
  kafka:
    producer:
      topic: ASYNC_TOPIC
    consumer:
      topic: ASYNC_TOPIC
#SPRING PROPERTIES
spring:
  kafka:
    bootstrap-servers: localhost:9092
    ssl:
      protocol: SSL
      trust-store-location: classpath:/store/kafka.server.truststore.jks
      trust-store-password: 123456
      key-store-location: classpath:/store/kafka.server.keystore.jks
      key-store-password: 123456
      key-password: 123456
    producer:
      retries: 0
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#LOGGING PROPERTIES
logging:
  level:
    root: INFO
